# Generated by Django 6.0.7 on 2026-07-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('task_karma_value', models.IntegerField(default=0)),
                ('difficulty_level', models.IntegerField(default=2)),
                ('task_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('task_name', models.CharField(max_length=255)),
                ('task_id', models.IntegerField(default=0)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('difficulty_level', models.IntegerField(default=2)),
            ],
        ),
    ]
